package edu.colostate.cs414.d.pizza.ui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

public class PizzaOrderingSystemUI extends javax.swing.JFrame {

    /**
     * Creates new form PizzaOrderingSystemUI
     */
    public PizzaOrderingSystemUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        placeOrderDialog = new javax.swing.JDialog();
        addOrderItemPanel = new javax.swing.JPanel();
        placeOrderLabel = new javax.swing.JLabel();
        placeOrderMenuScrollPane = new javax.swing.JScrollPane();
        placeOrderMenuList = new javax.swing.JList();
        addOrderItemButton = new javax.swing.JButton();
        itemQuantitySpinner = new javax.swing.JSpinner();
        viewCurrentOrderPanel = new javax.swing.JPanel();
        viewCurrentOrderLabel = new javax.swing.JLabel();
        viewCurrentOrderScrollPane = new javax.swing.JScrollPane();
        viewCurrentOrderList = new javax.swing.JList();
        removeOrderItemButton = new javax.swing.JButton();
        orderTotalLabel = new javax.swing.JLabel();
        placeOrderDoneButton = new javax.swing.JButton();
        loginDialog = new javax.swing.JDialog();
        loginPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        createModifyMenuDialog = new javax.swing.JDialog();
        createModifyMenuScrollPane = new javax.swing.JScrollPane();
        createModifyMenuList = new javax.swing.JList();
        createModifyMenuLabel = new javax.swing.JLabel();
        addMenuItemButton = new javax.swing.JButton();
        createModifyMenuDoneButton = new javax.swing.JButton();
        addMenuItemNameTextField = new javax.swing.JTextField();
        addMenuItemNameLabel = new javax.swing.JLabel();
        addMenuItemDescriptionLabel = new javax.swing.JLabel();
        addMenuItemDescriptionTextField = new javax.swing.JTextField();
        addMenuItemPriceLabel = new javax.swing.JLabel();
        addMenuItemPriceTextField = new javax.swing.JTextField();
        removeMenuItemButton = new javax.swing.JButton();
        confirmCreateMenuDoneDialog = new javax.swing.JDialog();
        confirmMenuScrollPane = new javax.swing.JScrollPane();
        confirmMenuList = new javax.swing.JList();
        confirmCreateMenuYesButton = new javax.swing.JButton();
        confirmDoneCreatingMenuLabel = new javax.swing.JLabel();
        confirmCreateMenuNoButton = new javax.swing.JButton();
        confirmAddMenuItemDialog = new javax.swing.JDialog();
        confirmAddMenuItemLabel = new javax.swing.JLabel();
        confirmAddMenuItemNameLabel = new javax.swing.JLabel();
        confirmAddMenuItemDescriptionLabel = new javax.swing.JLabel();
        confirmAddMenuItemPriceLabel = new javax.swing.JLabel();
        confirmAddMenuItemYesButton = new javax.swing.JButton();
        confirmAddMenuItemNoButton = new javax.swing.JButton();
        removeMenuItemDialog = new javax.swing.JDialog();
        removeMenuItemLabel = new javax.swing.JLabel();
        removeMenuItemNameLabel = new javax.swing.JLabel();
        removeMenuItemDescriptionLabel = new javax.swing.JLabel();
        removeMenuItemPriceLabel = new javax.swing.JLabel();
        removeMenuItemYesButton = new javax.swing.JButton();
        removeMenuItemNoButton = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        menuScrollPane = new javax.swing.JScrollPane();
        menuList = new javax.swing.JList();
        createModifyMenuButton = new javax.swing.JButton();
        setDailySpecialButton = new javax.swing.JButton();
        placeOrderPanel = new javax.swing.JPanel();
        placeOrderButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        placeOrderDialog.setModal(true);

        addOrderItemPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        placeOrderLabel.setText("Place order");

        placeOrderMenuList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        placeOrderMenuScrollPane.setViewportView(placeOrderMenuList);

        addOrderItemButton.setText("Add order item");

        itemQuantitySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        javax.swing.GroupLayout addOrderItemPanelLayout = new javax.swing.GroupLayout(addOrderItemPanel);
        addOrderItemPanel.setLayout(addOrderItemPanelLayout);
        addOrderItemPanelLayout.setHorizontalGroup(
            addOrderItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOrderItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addOrderItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placeOrderLabel)
                    .addComponent(placeOrderMenuScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addOrderItemPanelLayout.createSequentialGroup()
                        .addComponent(itemQuantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addOrderItemButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addOrderItemPanelLayout.setVerticalGroup(
            addOrderItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOrderItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(placeOrderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(placeOrderMenuScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addOrderItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOrderItemButton)
                    .addComponent(itemQuantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        viewCurrentOrderPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        viewCurrentOrderLabel.setText("View current order");

        viewCurrentOrderList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        viewCurrentOrderScrollPane.setViewportView(viewCurrentOrderList);

        removeOrderItemButton.setText("Remove order item");

        orderTotalLabel.setText("Total: $ 0.00");

        javax.swing.GroupLayout viewCurrentOrderPanelLayout = new javax.swing.GroupLayout(viewCurrentOrderPanel);
        viewCurrentOrderPanel.setLayout(viewCurrentOrderPanelLayout);
        viewCurrentOrderPanelLayout.setHorizontalGroup(
            viewCurrentOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCurrentOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewCurrentOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewCurrentOrderScrollPane)
                    .addGroup(viewCurrentOrderPanelLayout.createSequentialGroup()
                        .addGroup(viewCurrentOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewCurrentOrderLabel)
                            .addGroup(viewCurrentOrderPanelLayout.createSequentialGroup()
                                .addComponent(removeOrderItemButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderTotalLabel)))
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );
        viewCurrentOrderPanelLayout.setVerticalGroup(
            viewCurrentOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCurrentOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewCurrentOrderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewCurrentOrderScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewCurrentOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeOrderItemButton)
                    .addComponent(orderTotalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        placeOrderDoneButton.setText("Done");
        placeOrderDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderDoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout placeOrderDialogLayout = new javax.swing.GroupLayout(placeOrderDialog.getContentPane());
        placeOrderDialog.getContentPane().setLayout(placeOrderDialogLayout);
        placeOrderDialogLayout.setHorizontalGroup(
            placeOrderDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeOrderDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(placeOrderDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(placeOrderDialogLayout.createSequentialGroup()
                        .addComponent(addOrderItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewCurrentOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, placeOrderDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(placeOrderDoneButton)))
                .addContainerGap())
        );
        placeOrderDialogLayout.setVerticalGroup(
            placeOrderDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeOrderDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(placeOrderDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewCurrentOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addOrderItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(placeOrderDoneButton))
        );

        loginDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        loginDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                loginDialogWindowClosing(evt);
            }
        });

        loginPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        loginButton.setText("Log in");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(passwordLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(usernameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton))
        );

        javax.swing.GroupLayout loginDialogLayout = new javax.swing.GroupLayout(loginDialog.getContentPane());
        loginDialog.getContentPane().setLayout(loginDialogLayout);
        loginDialogLayout.setHorizontalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginDialogLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
        loginDialogLayout.setVerticalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginDialogLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(105, Short.MAX_VALUE)))
        );

        createModifyMenuDialog.setModal(true);

        createModifyMenuList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        createModifyMenuScrollPane.setViewportView(createModifyMenuList);

        createModifyMenuLabel.setText("Create/modify menu");

        addMenuItemButton.setText("Add menu item");
        addMenuItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuItemButtonActionPerformed(evt);
            }
        });

        createModifyMenuDoneButton.setText("Done");
        createModifyMenuDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createModifyMenuDoneButtonActionPerformed(evt);
            }
        });

        addMenuItemNameLabel.setText("Name");

        addMenuItemDescriptionLabel.setText("Description");

        addMenuItemPriceLabel.setText("Price");

        removeMenuItemButton.setText("Remove menu item");
        removeMenuItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMenuItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createModifyMenuDialogLayout = new javax.swing.GroupLayout(createModifyMenuDialog.getContentPane());
        createModifyMenuDialog.getContentPane().setLayout(createModifyMenuDialogLayout);
        createModifyMenuDialogLayout.setHorizontalGroup(
            createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createModifyMenuDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createModifyMenuDialogLayout.createSequentialGroup()
                        .addComponent(addMenuItemNameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(createModifyMenuDialogLayout.createSequentialGroup()
                        .addGroup(createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createModifyMenuScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createModifyMenuLabel)
                            .addComponent(addMenuItemButton)
                            .addGroup(createModifyMenuDialogLayout.createSequentialGroup()
                                .addGroup(createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addMenuItemDescriptionLabel)
                                    .addComponent(addMenuItemPriceLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addMenuItemDescriptionTextField)
                                    .addGroup(createModifyMenuDialogLayout.createSequentialGroup()
                                        .addComponent(addMenuItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(addMenuItemPriceTextField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createModifyMenuDialogLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(createModifyMenuDoneButton))
                            .addGroup(createModifyMenuDialogLayout.createSequentialGroup()
                                .addComponent(removeMenuItemButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        createModifyMenuDialogLayout.setVerticalGroup(
            createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createModifyMenuDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createModifyMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createModifyMenuScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeMenuItemButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMenuItemNameLabel)
                    .addComponent(addMenuItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMenuItemDescriptionLabel)
                    .addComponent(addMenuItemDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMenuItemPriceLabel)
                    .addComponent(addMenuItemPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createModifyMenuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMenuItemButton)
                    .addComponent(createModifyMenuDoneButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirmCreateMenuDoneDialog.setModal(true);

        confirmMenuList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        confirmMenuScrollPane.setViewportView(confirmMenuList);

        confirmCreateMenuYesButton.setText("Yes");
        confirmCreateMenuYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmCreateMenuYesButtonActionPerformed(evt);
            }
        });

        confirmDoneCreatingMenuLabel.setText("Are you done creating the menu?");

        confirmCreateMenuNoButton.setText("No");
        confirmCreateMenuNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmCreateMenuNoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmCreateMenuDoneDialogLayout = new javax.swing.GroupLayout(confirmCreateMenuDoneDialog.getContentPane());
        confirmCreateMenuDoneDialog.getContentPane().setLayout(confirmCreateMenuDoneDialogLayout);
        confirmCreateMenuDoneDialogLayout.setHorizontalGroup(
            confirmCreateMenuDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmCreateMenuDoneDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confirmCreateMenuDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmMenuScrollPane)
                    .addGroup(confirmCreateMenuDoneDialogLayout.createSequentialGroup()
                        .addGroup(confirmCreateMenuDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmDoneCreatingMenuLabel)
                            .addGroup(confirmCreateMenuDoneDialogLayout.createSequentialGroup()
                                .addComponent(confirmCreateMenuYesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmCreateMenuNoButton)))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
        );
        confirmCreateMenuDoneDialogLayout.setVerticalGroup(
            confirmCreateMenuDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmCreateMenuDoneDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmMenuScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmDoneCreatingMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmCreateMenuDoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmCreateMenuYesButton)
                    .addComponent(confirmCreateMenuNoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirmAddMenuItemDialog.setModal(true);

        confirmAddMenuItemLabel.setText("Add item?");

        confirmAddMenuItemNameLabel.setText("Name: ");

        confirmAddMenuItemDescriptionLabel.setText("Description: ");

        confirmAddMenuItemPriceLabel.setText("Price: $");

        confirmAddMenuItemYesButton.setText("Yes");
        confirmAddMenuItemYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddMenuItemYesButtonActionPerformed(evt);
            }
        });

        confirmAddMenuItemNoButton.setText("No");
        confirmAddMenuItemNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddMenuItemNoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmAddMenuItemDialogLayout = new javax.swing.GroupLayout(confirmAddMenuItemDialog.getContentPane());
        confirmAddMenuItemDialog.getContentPane().setLayout(confirmAddMenuItemDialogLayout);
        confirmAddMenuItemDialogLayout.setHorizontalGroup(
            confirmAddMenuItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmAddMenuItemDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confirmAddMenuItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmAddMenuItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(confirmAddMenuItemDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmAddMenuItemNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmAddMenuItemPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmAddMenuItemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(confirmAddMenuItemDialogLayout.createSequentialGroup()
                        .addComponent(confirmAddMenuItemYesButton)
                        .addGap(18, 18, 18)
                        .addComponent(confirmAddMenuItemNoButton)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        confirmAddMenuItemDialogLayout.setVerticalGroup(
            confirmAddMenuItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmAddMenuItemDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmAddMenuItemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmAddMenuItemNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmAddMenuItemDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmAddMenuItemPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmAddMenuItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmAddMenuItemYesButton)
                    .addComponent(confirmAddMenuItemNoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        removeMenuItemDialog.setModal(true);

        removeMenuItemLabel.setText("Remove menu item?");

        removeMenuItemNameLabel.setText("Name: ");

        removeMenuItemDescriptionLabel.setText("Description: ");

        removeMenuItemPriceLabel.setText("Price: $");

        removeMenuItemYesButton.setText("Yes");
        removeMenuItemYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMenuItemYesButtonActionPerformed(evt);
            }
        });

        removeMenuItemNoButton.setText("No");
        removeMenuItemNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMenuItemNoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeMenuItemDialogLayout = new javax.swing.GroupLayout(removeMenuItemDialog.getContentPane());
        removeMenuItemDialog.getContentPane().setLayout(removeMenuItemDialogLayout);
        removeMenuItemDialogLayout.setHorizontalGroup(
            removeMenuItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeMenuItemDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removeMenuItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeMenuItemLabel)
                    .addComponent(removeMenuItemNameLabel)
                    .addComponent(removeMenuItemDescriptionLabel)
                    .addComponent(removeMenuItemPriceLabel)
                    .addGroup(removeMenuItemDialogLayout.createSequentialGroup()
                        .addComponent(removeMenuItemYesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeMenuItemNoButton)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        removeMenuItemDialogLayout.setVerticalGroup(
            removeMenuItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeMenuItemDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeMenuItemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeMenuItemNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeMenuItemDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeMenuItemPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removeMenuItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeMenuItemYesButton)
                    .addComponent(removeMenuItemNoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menuLabel.setText("Menu");

        menuList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuScrollPane.setViewportView(menuList);

        createModifyMenuButton.setText("Create/Modify menu");
        createModifyMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createModifyMenuButtonActionPerformed(evt);
            }
        });

        setDailySpecialButton.setText("Set daily special");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuScrollPane)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(menuLabel)
                            .addComponent(createModifyMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setDailySpecialButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 161, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createModifyMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setDailySpecialButton)
                .addContainerGap())
        );

        placeOrderPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        placeOrderButton.setText("Place order");
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout placeOrderPanelLayout = new javax.swing.GroupLayout(placeOrderPanel);
        placeOrderPanel.setLayout(placeOrderPanelLayout);
        placeOrderPanelLayout.setHorizontalGroup(
            placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(placeOrderButton)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        placeOrderPanelLayout.setVerticalGroup(
            placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(placeOrderButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoutButton.setText("Log out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(placeOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(placeOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        placeOrderDialog.pack();
        placeOrderDialog.setVisible(true);
    }//GEN-LAST:event_placeOrderButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        loginDialog.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        loginDialog.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void placeOrderDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderDoneButtonActionPerformed
        // TODO add your handling code here:
        placeOrderDialog.setVisible(false);
    }//GEN-LAST:event_placeOrderDoneButtonActionPerformed

    private void loginDialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loginDialogWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_loginDialogWindowClosing

    private void createModifyMenuDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createModifyMenuDoneButtonActionPerformed
        // TODO add your handling code here:
        confirmCreateMenuDoneDialog.pack();
        confirmCreateMenuDoneDialog.setVisible(true);
    }//GEN-LAST:event_createModifyMenuDoneButtonActionPerformed

    private void createModifyMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createModifyMenuButtonActionPerformed
        // TODO add your handling code here:
        createModifyMenuDialog.pack();
        createModifyMenuDialog.setVisible(true);
    }//GEN-LAST:event_createModifyMenuButtonActionPerformed

    private void addMenuItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuItemButtonActionPerformed
        // TODO add your handling code here:
        confirmAddMenuItemDialog.pack();
        confirmAddMenuItemDialog.setVisible(true);
    }//GEN-LAST:event_addMenuItemButtonActionPerformed

    private void confirmCreateMenuYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmCreateMenuYesButtonActionPerformed
        // TODO add your handling code here:
        confirmCreateMenuDoneDialog.setVisible(false);
        createModifyMenuDialog.setVisible(false);
    }//GEN-LAST:event_confirmCreateMenuYesButtonActionPerformed

    private void confirmCreateMenuNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmCreateMenuNoButtonActionPerformed
        // TODO add your handling code here:
        confirmCreateMenuDoneDialog.setVisible(false);
    }//GEN-LAST:event_confirmCreateMenuNoButtonActionPerformed

    private void confirmAddMenuItemYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddMenuItemYesButtonActionPerformed
        // TODO add your handling code here:
        confirmAddMenuItemDialog.setVisible(false);
    }//GEN-LAST:event_confirmAddMenuItemYesButtonActionPerformed

    private void confirmAddMenuItemNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddMenuItemNoButtonActionPerformed
        // TODO add your handling code here:
        confirmAddMenuItemDialog.setVisible(false);
    }//GEN-LAST:event_confirmAddMenuItemNoButtonActionPerformed

    private void removeMenuItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMenuItemButtonActionPerformed
        // TODO add your handling code here:
        removeMenuItemDialog.pack();
        removeMenuItemDialog.setVisible(true);
    }//GEN-LAST:event_removeMenuItemButtonActionPerformed

    private void removeMenuItemYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMenuItemYesButtonActionPerformed
        // TODO add your handling code here:
        removeMenuItemDialog.setVisible(false);
    }//GEN-LAST:event_removeMenuItemYesButtonActionPerformed

    private void removeMenuItemNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMenuItemNoButtonActionPerformed
        // TODO add your handling code here:
        removeMenuItemDialog.setVisible(false);
    }//GEN-LAST:event_removeMenuItemNoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaOrderingSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaOrderingSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaOrderingSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaOrderingSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PizzaOrderingSystemUI posUI = new PizzaOrderingSystemUI();
                posUI.setVisible(false);
                posUI.loginDialog.pack();
                posUI.loginDialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMenuItemButton;
    private javax.swing.JLabel addMenuItemDescriptionLabel;
    private javax.swing.JTextField addMenuItemDescriptionTextField;
    private javax.swing.JLabel addMenuItemNameLabel;
    private javax.swing.JTextField addMenuItemNameTextField;
    private javax.swing.JLabel addMenuItemPriceLabel;
    private javax.swing.JTextField addMenuItemPriceTextField;
    private javax.swing.JButton addOrderItemButton;
    private javax.swing.JPanel addOrderItemPanel;
    private javax.swing.JLabel confirmAddMenuItemDescriptionLabel;
    private javax.swing.JDialog confirmAddMenuItemDialog;
    private javax.swing.JLabel confirmAddMenuItemLabel;
    private javax.swing.JLabel confirmAddMenuItemNameLabel;
    private javax.swing.JButton confirmAddMenuItemNoButton;
    private javax.swing.JLabel confirmAddMenuItemPriceLabel;
    private javax.swing.JButton confirmAddMenuItemYesButton;
    private javax.swing.JDialog confirmCreateMenuDoneDialog;
    private javax.swing.JButton confirmCreateMenuNoButton;
    private javax.swing.JButton confirmCreateMenuYesButton;
    private javax.swing.JLabel confirmDoneCreatingMenuLabel;
    private javax.swing.JList confirmMenuList;
    private javax.swing.JScrollPane confirmMenuScrollPane;
    private javax.swing.JButton createModifyMenuButton;
    private javax.swing.JDialog createModifyMenuDialog;
    private javax.swing.JButton createModifyMenuDoneButton;
    private javax.swing.JLabel createModifyMenuLabel;
    private javax.swing.JList createModifyMenuList;
    private javax.swing.JScrollPane createModifyMenuScrollPane;
    private javax.swing.JSpinner itemQuantitySpinner;
    private javax.swing.JButton loginButton;
    private javax.swing.JDialog loginDialog;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JList menuList;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JScrollPane menuScrollPane;
    private javax.swing.JLabel orderTotalLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JDialog placeOrderDialog;
    private javax.swing.JButton placeOrderDoneButton;
    private javax.swing.JLabel placeOrderLabel;
    private javax.swing.JList placeOrderMenuList;
    private javax.swing.JScrollPane placeOrderMenuScrollPane;
    private javax.swing.JPanel placeOrderPanel;
    private javax.swing.JButton removeMenuItemButton;
    private javax.swing.JLabel removeMenuItemDescriptionLabel;
    private javax.swing.JDialog removeMenuItemDialog;
    private javax.swing.JLabel removeMenuItemLabel;
    private javax.swing.JLabel removeMenuItemNameLabel;
    private javax.swing.JButton removeMenuItemNoButton;
    private javax.swing.JLabel removeMenuItemPriceLabel;
    private javax.swing.JButton removeMenuItemYesButton;
    private javax.swing.JButton removeOrderItemButton;
    private javax.swing.JButton setDailySpecialButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel viewCurrentOrderLabel;
    private javax.swing.JList viewCurrentOrderList;
    private javax.swing.JPanel viewCurrentOrderPanel;
    private javax.swing.JScrollPane viewCurrentOrderScrollPane;
    // End of variables declaration//GEN-END:variables
}
